add --threads option
Last-Order/kkr pull request #2
Opened 2020-10-16 10:59 UTC by kagurazakakotori

2020-10-16 11:41 UTC, Last-Order requested changes
感觉没啥问题，改下输出的地方吧。
感谢贡献！

2020-10-16 11:41 UTC, Last-Order commented on src/core/downloader.ts
> +        this.logger.info(`使用至多 ${this.maxThreads} 线程下载`);
`this.logger.debug()`吧，这个没啥必要必须打印

2020-10-16 11:41 UTC, Last-Order commented on src/core/live_downloader.ts
> +        this.logger.info(`使用至多 ${this.maxRunningThreads} 线程下载`);
同上

2020-10-17 02:21 UTC, kagurazakakotori commented on src/core/downloader.ts
> +        this.logger.info(`使用至多 ${this.maxThreads} 线程下载`);
已修复

2020-10-17 02:23 UTC, merged

2020-10-17 02:24 UTC, Last-Order commented
谢谢

2020-10-18 02:57 UTC, Last-Order commented
Landed in 1.1.19.